baseURL = 'https://yawnick.de/'
languageCode = 'en-us'
title = "Yawnick"

theme = 'soho-yn'

enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[params]
author = 'Jannik'
description = 'Welcome to my cache.'
profilePicture = 'images/TheDiabolo.jpeg'
themeColor = '#033855'
copyright = 'Jannik'

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

 # [[menu.main]]
 # name = "Projects"
 # weight = 150
 # identifier = "projects"
 # url = "/projects/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"
