baseURL = 'https://yawnick.de/'
languageCode = 'en-us'
title = "Yawnick"

theme = 'soho-yn'

enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[params]
author = 'Jannik'
description = 'Welcome to my cache.'
profilePicture = 'images/TheDiabolo.jpeg'
#themeColor = '#033855'
themeColor = '#49757a'
copyright = 'Jannik'

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Projects"
  weight = 150
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 1000
  url = "/about/"

[taxonomies]
category = "categories"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "friendly"
  tabWidth = 4
  
  [markup.goldmark.renderer]
  unsafe = true


defaultContentLanguage = 'en'
[languages]
  [languages.en]
    weight = 1
    languageName = "🇺🇸"
  #[languages.de]
  #  weight = 2
  #  languageName = "🇩🇪"